{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <test_class.TestClass object at 0x0000023809FFC100>\n\n    def test_two(self):\n        print(2222222222)\n        x = \"hello\"\n>       assert hasattr(x, 'check')  # hasattr() 函数用于判断对象是否包含对应的属性。\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest_class.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "b5e50f4e-a483-47d5-8635-e0bd526b96a8-attachment.txt", "type": "text/plain"}], "start": 1602222523427, "stop": 1602222523428, "uuid": "b7444845-ceb5-4f2a-823a-589f11ff99f3", "historyId": "cca081f1c320efa44fffe5d884236360", "testCaseId": "9e2269e6af13cd7747e18ca37f3d74ba", "fullName": "test_class.TestClass#test_two", "labels": [{"name": "suite", "value": "test_class"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "DESKTOP-MSC5KCU"}, {"name": "thread", "value": "4988-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_class"}]}